### ISSUE TITLE
See images for unconfirmed inscriptions

### ISSUE THREAD

**Issue by dannydeezy** [dannydeezy/nosft#1]
It would be nice to see the contents of your inscriptions while they're in mempool - currently they only show up when confirmed on chain

**Comment by dannydeezy** [comment]
done, it looks up to the deezy api directly

**Comment by dannydeezy** [comment]
but would be nice to have a more sustainable solution that works for non-deezy generated collections

**Comment by habibitcoin** [comment]
Should close and leverage https://github.com/dannydeezy/nosft/issues/99
