### ISSUE TITLE
Inscription detail page

### ISSUE THREAD

**Issue by andredevjs** [dannydeezy/nosft#103]
# Inscription details

Adds a new page for view details

---

### What problem are you trying to solve?
* _There are plenty of features we can add to a inscription, it can be send, boost, sell, or buy even auction. The problem that we have right now is that we have a list of inscriptions, and there isn't too much space to play with all of those features, because of that, we would like to have a specific inscriptions page, in which we can view more details of the inscription like collection and also do more actiions_

### Why should we solve it?
* _Why is this an important problem for us to solve?_  Because we have some open PRs that integrates nostr and also some others to sign psbt, this means we can now buy and sell from our website if we achieve this!
* _Is it a big enough problem to solve?_ -
* _Should we solve it now, or later?_ This is a blocker to add more features

### How do you propose to solve it?
* When a user clicks on a inscription we are going to have some dynamic path that fetches information about the inscription and renders the inscription in the page
* If the user owns the inscription, it should be able to send it, or sell it (once we integrate this)
* If the user doesn't own the inscription and it is for sell, we can allow the user to buy it

### What could go wrong?
* _What risks does your proposed change entail?_ That if server code fails, it will break the UI, also we need to be careful of the utxo managment.
* _How could this system fail, and what would be the impact if it did?_ People cannot send/sell/buy inscriptions

**Comment by habibitcoin** [comment]
Will be completed in release 0.2
