### ISSUE TITLE
PSBT Signing Resulting in Improperly Finalized Txs

### ISSUE THREAD

**Issue by habibitcoin** [dannydeezy/nosft#117]
Anyone here done work w/ PSBTs? Having an issue where the PSBTs we are generating in mv2 are actually "finalized" it seems somehow, so when you try to buy one of our ordinals on OpenOrdex, it gives an error that "all signatures are finalized"

If you take a look at one of our PSBTS (https://openordex.org/inscription?number=13c44582fcaaaa717cef8956d7548ccf25099a6a2d2e6e7684746721726732e1i0):
`cHNidP8BAF4CAAAAAZWfzLIXc1zp8TbQrj3z2hNWDES/kQtCEvJtUD8UatbjAAAAAAD/////ASChBwAAAAAAIlEgjRBVFdkOll+Llvk6CoHu1TRh2fvrpF1uY8Wcqc7/NisAAAAAAAEAXgIAAAABGCPFwzeDVKKbFd93XuiuUeicUbaKMfuDgsbmK/HO5voAAAAAAP////8BnwIAAAAAAAAiUSCNEFUV2Q6WX4uW+ToKge7VNGHZ++ukXW5jxZypzv82KwAAAAABASufAgAAAAAAACJRII0QVRXZDpZfi5b5OgqB7tU0Ydn766RdbmPFnKnO/zYrAQhCAUDHHVJ0K5Wmd2a1B4RoHlzfA/SlXkb/yGg2EqfuLWRj9MIWhkqZjyZgYRcKdVPhM0cT0p7Nb1ZysLxSKMXOhITrAAA=`
vs one generated externally(https://openordex.org/inscription?number=58b91200e443bed1f17cc909e6672403aa317b3c6a02e594e1459e7967048ec9i0):
`cHNidP8BAF4CAAAAAfsBZvuuLlNBPbRW8y3G1NbD987TDi2FBVJNrrQ5YVwmAQAAAAABAAAAAZ+7DQAAAAAAIlEgiqMrl7zEj5mM8RXwMOG1OKBsg9fsudrZufXrIQt5OmMAAAAAAAEBKxAnAAAAAAAAIlEgiqMrl7zEj5mM8RXwMOG1OKBsg9fsudrZufXrIQt5OmMBCEMBQaUymjyf7pGMkBBVMXpyXsHnBAJ4DRWYE5HxoY1fYQ/1hKVLnv1KV1iyT7x5+VvAMP6co/G+T+i9j1UibK1xqNeDAAA=`

You'll notice that when importing into Sparrow, the externally generated one has 0/1 signatures whereas ours has 1/1 signatures. Both have the witnesses data populated correctly though.

Will also ask some openordex devs if I can get ahold of em.

Relevant code portion:
```
      const sigHash = virtualToSign.__CACHE.__TX.hashForWitnessV1(
         0,
         [virtualToSign.data.inputs[0].witnessUtxo.script],
         [virtualToSign.data.inputs[0].witnessUtxo.value],
         // eslint-disable-next-line no-bitwise
         bitcoin.Transaction.SIGHASH_SINGLE | bitcoin.Transaction.SIGHASH_ANYONECANPAY
      );


      const sign = await signSigHash({sigHash});
      virtualToSign.updateInput(0, {
          tapKeySig: serializeTaprootSignature(Buffer.from(sign, "hex"));
      });

      virtualToSign.finalizeAllInputs();
```

Can try buying with bc1p7u8nsdrdqam4u4huvryzgageg3vfc2mlcfsxrmezl76rnsukwg6qsa2uqr to reproduce

![image](https://user-images.githubusercontent.com/114780316/231915743-b43cce76-93f2-4817-8c00-088bd8754d2a.png)

**Comment by dannydeezy** [comment]
perhaps remove the `virtualToSign.finalizeAllInputs();` line

**Comment by habibitcoin** [comment]
@dannydeezy tried that, but results in the witness missing, and the signature still present

+ OpenOrdex unhappy 
<img width="462" alt="image" src="https://user-images.githubusercontent.com/114780316/231939120-c6956afe-d0d2-4e77-b105-e505e93527bd.png">
 
 
 ```
cHNidP8BAF4CAAAAAZWfzLIXc1zp8TbQrj3z2hNWDES/kQtCEvJtUD8UatbjAAAAAAD/////AY+fBwAAAAAAIlEgjRBVFdkOll+Llvk6CoHu1TRh2fvrpF1uY8Wcqc7/NisAAAAAAAEAXgIAAAABGCPFwzeDVKKbFd93XuiuUeicUbaKMfuDgsbmK/HO5voAAAAAAP////8BnwIAAAAAAAAiUSCNEFUV2Q6WX4uW+ToKge7VNGHZ++ukXW5jxZypzv82KwAAAAABASufAgAAAAAAACJRII0QVRXZDpZfi5b5OgqB7tU0Ydn766RdbmPFnKnO/zYrAQMEgwAAAAETQJjsHmlj/lPw6ubR/doFpg8rIp760VdOtnAbrS3ana/wua3MOzejWMRoXqHXmVJtfgQIws8VHlvobNxcUIm0dL0AAA==
 ```

**Comment by habibitcoin** [comment]
Tried that one earlier as well, no go :/

"Error: Expected property "signature" of type Buffer(Length: 64), got Buffer(Length: 65)"

**Comment by dannydeezy** [comment]
> Tried that one earlier as well, no go :/
> 
> "Error: Expected property "signature" of type Buffer(Length: 64), got Buffer(Length: 65)"

ah, this is a known bug in bitcoinjs-lib 
https://github.com/bitcoinjs/bitcoinjs-lib/issues/1902

**Comment by dannydeezy** [comment]
> > Tried that one earlier as well, no go :/
> > "Error: Expected property "signature" of type Buffer(Length: 64), got Buffer(Length: 65)"
> 
> ah, this is a known bug in bitcoinjs-lib [bitcoinjs/bitcoinjs-lib#1902](https://github.com/bitcoinjs/bitcoinjs-lib/issues/1902)

we could try to use this alternative psbt library instead, or wait for the bitcoinjs-lib fix to be merged

https://www.npmjs.com/package/psbt

**Comment by habibitcoin** [comment]
Fix found, and test left in https://github.com/bitcoinjs/bitcoinjs-lib/pull/1884#issuecomment-1509384667
