### ISSUE TITLE
No way of viewing the full outpoint of a non-inscribed UTXO

### ISSUE THREAD

**Issue by dannydeezy** [dannydeezy/nosft#131]
I should be able to click somewhere to get a link to mempool.space or something so i can investigate a transaction that doesn't have an inscription on it

**Comment by dannydeezy** [comment]
no link for me to click

<img width="323" alt="Screenshot 2023-04-19 at 3 45 08 PM" src="https://user-images.githubusercontent.com/43550949/233215709-38a893eb-a9ee-4fea-bd09-452eece9310e.png">

**Comment by habibitcoin** [comment]
https://github.com/dannydeezy/nosft/commit/0f49b8b5b5c4ebdca6cdaaad0dfb458b8a3349c7 completed @dannydeezy !
