### ISSUE TITLE
TypeError: window.nostr.signSchnorr is not a function

### ISSUE THREAD

**Issue by quantum-proof** [dannydeezy/nosft#16]
Receiving the above type error while trying to send the ords to a different wallet (ie. Sparrow).

![Screenshot 2023-02-19 at 3 33 46 AM](https://user-images.githubusercontent.com/101009469/219885155-ce68d5ea-113b-4243-a4b2-982702d4a5c6.png)

**Comment by dannydeezy** [comment]
you just need to update your Alby extension to version 1.27 or later. In `chrome://extensions` Developer Mode On, Update
