### ISSUE TITLE
Make it work with Metamask as the wallet

### ISSUE THREAD

**Issue by dannydeezy** [dannydeezy/nosft#29]
Some other websites like generative.xyz and ordswap.io are adding a Metamask integration. It's kinda janky if I understand - they are generating a private key from a signature of the metamask wallet. But if this is going to be the standard, then I guess we can adopt it as well

**Comment by LunarMiolk** [comment]
Should be aware that ordswap's method requires the user to store their BTC private key in local storage. This is horrendously insecure.

I would very much hope this does not become the standard.

**Comment by habibitcoin** [comment]
https://github.com/dannydeezy/nosft/pull/79
