### ISSUE TITLE
Integrate with Deezy Boost

### ISSUE THREAD

**Issue by dannydeezy** [dannydeezy/nosft#49]
When an ordinal runs low on its satoshi value, it become unable to pay for sending itself. To solve this issue, Deezy has added a boost API endpoint.
https://docs.deezy.io/#tag/Boost

To use the boost, the user creates a PSBT, submits it to Deezy, and then Deezy provides a lightning invoice. When user pays the lightning invoice then Deezy completes the PSBT by adding a input to fund the send and top up the ordinal's satoshi value

This should be seamless for the user. My proposal is something like this:

- On the Send modal, have an "Advanced options" section
- In advanced options have a checkbox "Replenish Juice" or something

- If this is checked, don't do the normal send flow, instead use the Deezy Boost send flow 
- This flow involves paying a lightning invoice, which should show a modal  similar to below (one-click Pay with alby browser extension, or expand to via QR code).

![Screenshot 2023-03-13 at 9 54 22 AM](https://user-images.githubusercontent.com/43550949/224771267-733c5c3e-697b-4717-b221-097511bc9ac5.png)

**Comment by dannydeezy** [comment]
here is some example code how to generate a valid PSBT on the client side (which will be posted to the API endpoint)
```
const hdNode = bip32.fromSeed(Buffer.from(testSeed, 'hex'), bitcoin.networks.testnet)
    const psbt = new bitcoin.Psbt({ network: bitcoin.networks.testnet })
    psbt.addInput({
        hash: '0e9b81779c88b93d69564483676be61057178f286ae4a6d45a93b5dec9a3a035',
        index: 0
    })
    const RAW_ADDR = 'tb1qudccev4s0n0uckpfetqrqsvctl6qt0dgh2xe78'
    const addr = bitcoin.address.fromBech32(RAW_ADDR)
    psbt.updateInput(0, {
        // Need the full txHex of the input's transaction here... 
        nonWitnessUtxo: Buffer.from('02000000000101b667693b2c390a1a471470de5b84149ae813b27aa3d82110ce1f3784505f35b60100000000feffffff022c01000000000000160014e3718cb2b07cdfcc5829cac03041985ff405bda8b2430f0000000000160014ad198770eed2273c50ec6d450fc8476496bd7aa8024730440220679eb1e45d36122c5c6c55bad8471efdb31182f72a76154d30603e938b503218022041c529d0c533f8ef8e096b46a216a7a9907d5447b2fb9f7aafa7d36f5c8e4123012103bccfc8d7762460d30176e62e4282c8f1b0f11eb5fdbd59d6ef9fae3abee93271b4f92400', 'hex'),
        witnessUtxo: {
            script: addr.data,
            value: 300
        },
        sighashType: bitcoin.Transaction.SIGHASH_SINGLE | bitcoin.Transaction.SIGHASH_ANYONECANPAY
    })
    psbt.addOutput({
        address: RAW_ADDR,
        value: 10000
    })
    const keypair = hdNode.derivePath("m/84'/1'/0'/0/0")
    psbt.signInput(0, keypair, [bitcoin.Transaction.SIGHASH_SINGLE | bitcoin.Transaction.SIGHASH_ANYONECANPAY])
    psbt.finalizeInput(0)
    console.log(psbt.toHex())
    ```

**Comment by topether21** [comment]
In progress

**Comment by dannydeezy** [comment]
I've done this here https://github.com/dannydeezy/nosft/pull/148 @topether21
