### ISSUE TITLE
Parallelize utxo loading

### ISSUE THREAD

**Issue by dannydeezy** [dannydeezy/nosft#6]
Its done serially now but should be parallelized

**Comment by Uthpala** [comment]
I am going to pick this one. I am going to do the first 10 utxos in promise all and the rest I will do in another promise all

**Comment by andredevjs** [comment]
This one is already done. We would like to have infinite scrolling for this, so that we load them by chunks and not get rate limited.

**Comment by andredevjs** [comment]
Done here: https://github.com/dannydeezy/nosft/pull/33
