### ISSUE TITLE
Display ordinal text inside div instead of an iframe

### ISSUE THREAD

**Issue by andredevjs** [dannydeezy/nosft#64]
Right now, since we don't control the content of the iframe, text ordinals looks like this:

<img width="304" alt="Screenshot 2023-03-15 at 07 23 03" src="https://user-images.githubusercontent.com/97211514/225321583-8fb33197-90b9-4e74-9b86-f8c7df114157.png">

But, if we get the content with axios, and push it to the div, we have better control to display the content for example:

```
 const isText = /(^text\/plain)[a-zA-Z0-9_]*/gm.test(utxo.content_type);

if (isText) {
            axios.get(`${ORDINALS_EXPLORER_URL}/content/${utxo.inscriptionId}`).then((res) => {
                handleLoad();
                document.getElementById(`iframe-${utxo.inscriptionId}`).innerHTML = res.data;
            });

            return (
                <div
                    id={`iframe-${utxo.inscriptionId}`}
                    style={{ visibility: loading ? "hidden" : "visible", backgroundColor: "red" }}
                />
            );
        }

```

Which looks much better

<img width="339" alt="Screenshot 2023-03-15 at 07 22 23" src="https://user-images.githubusercontent.com/97211514/225321369-3a63dc6a-f0eb-44b7-aa4d-9d5dde191dc2.png">

What u guys think?
@Uthpala @habibitcoin @dannydeezy @topether21

**Comment by topether21** [comment]
Good observation. I agree @andredevjs.

**Comment by habibitcoin** [comment]
Yup, agreed! 100% 

Also addresses our issue where ordinals.com and turbo were applying subtle styling differences; instead, we can just apply our styling

**Comment by topether21** [comment]
I can continue with this @andredevjs

**Comment by topether21** [comment]
Can you provide an address with an example of ordinal text? @andredevjs
